# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
